"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cookie_parser_1 = __importDefault(require("cookie-parser"));
const cors_1 = __importDefault(require("cors"));
const twitch_routes_1 = __importDefault(require("./twitch/twitch-routes"));
const steam_routes_1 = __importDefault(require("./steam/steam-routes"));
const twitch_auth_routes_1 = __importDefault(require("./twitch/twitch-auth-routes"));
const steam_1 = require("./steam/steam");
const dotenv_1 = require("dotenv");
(0, dotenv_1.configDotenv)();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use((0, cookie_parser_1.default)("some super secret thing, please do not copy this"));
(0, steam_1.cacheAllOwnedApps)();
app.use('/api/v1/twitch/', twitch_routes_1.default);
app.use('/api/v1/twitch/', twitch_auth_routes_1.default);
app.use('/api/v1/steam/', steam_routes_1.default);
app.listen(4243, () => console.log(`${Date.now()}: crispytaytortot.com NodeJS server listening on port 4243!`));
